####################
#     Metadata     #
####################

[project]
name = "waka-readme"
version = "0.2.1"
description = "Wakatime Weekly Metrics on your Profile Readme."
license = { text = "MIT" }
readme = "README.md"
keywords = ["readme", "profile-page", "wakatime"]
authors = [{ name = "Athul Cyriac Ajay", email = "athul8720@gmail.com" }]
maintainers = [{ name = "Jovial Joe Jayarson" }]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python",
    "Typing :: Typed",
]
requires-python = ">=3.11"
dependencies = ["faker>=19.1.0", "pygithub>=1.59.0", "requests>=2.31.0"]

[project.urls]
Homepage = "https://github.com/athul/waka-readme"
Documentation = "https://github.com/athul/waka-readme#readme"
Repository = "https://github.com/athul/waka-readme"
Changelog = "https://github.com/athul/waka-readme/commits/master"


#############################
#   Optional Dependencies   #
#############################

[project.optional-dependencies]
dev = ["loguru>=0.7.0", "python-dotenv>=1.0.0"]
tooling = ["bandit>=1.7.5", "black>=23.7.0", "ruff>=0.0.278"]

####################
#  Configurations  #
####################

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.bandit]
exclude_dirs = [".github", ".pytest_cache", ".tox", ".vscode", "site", "tests"]

[tool.ruff]
line-length = 100

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.isort]
force-sort-within-sections = true
relative-imports-order = "closest-to-furthest"
