name: Update WakaTime Stats

on:
  schedule:
    # Runs every day at 12:00 UTC
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Update README with WakaTime Stats
        uses: athul/waka-readme@v2.1.1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
